# Generated by Django 4.2.8 on 2023-12-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "academic_year",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.academicyear"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("person", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="schools.person")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.school")),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.subject")),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.teacher")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "grade_level",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.gradelevel"),
                ),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.parent")),
                ("person", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="schools.person")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.school")),
            ],
        ),
        migrations.AddField(
            model_name="parent",
            name="person",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="schools.person"),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.school")),
            ],
        ),
        migrations.CreateModel(
            name="ExamScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField()),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.exam")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.student")),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="lessons",
            field=models.ManyToManyField(to="schools.lesson"),
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_of_week", models.CharField(max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("class_name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.class")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.subject")),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.school"),
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(to="schools.student"),
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.teacher"),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("present", models.BooleanField(default=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="schools.student")),
            ],
        ),
    ]
