# Generated by Django 4.2.11 on 2024-03-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menuitem_deps_remove_menuitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='groups',
            new_name='group',
        ),
    ]
